x-db-env: &x-db-env
    DB_PASSWORD: ${DB_PASSWORD}
    DB_USERNAME: ${DB_USERNAME}
    DB_NAME: ${DB_NAME}
    DB_HOST: db
    DB_PORT: 5432

# docker/go/Dockerfile is a generic that compiles main.go at
# cmd/<SERVICE> and executes it. 
services:
  observer:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      args:
        SERVICE: observer
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
      db_setup:
        condition: service_completed_successfully
    environment:
      <<: *x-db-env
        

  db:
    container_name: db
    image: postgres:16
    restart: always
    shm_size: 128mb
    volumes:
      - db:/data/storage
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USERNAME -d $$DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PGDATA: /data/storage
      <<: *x-db-env

  db_setup:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      args:
        SERVICE: dbsetup
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      <<: *x-db-env
        
networks:
  db:
    driver: bridge

volumes:
  db:
