x-env: &shared-env
  env_file:
    - .env

services:
  observer:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      args:
        SERVICE: observer
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
      db_setup:
        condition: service_completed_successfully
    !!merge <<: *shared-env

  db:
    container_name: db
    image: postgres:16
    restart: always
    shm_size: 128mb
    volumes:
      - db:/data/postgres
    ports:
      - ${DB_HOST_PORT}:${DB_DOCKER_PORT}
    networks:
      - db
    !!merge <<: *shared-env
    environment:
      PGDATA: ${DB_DATA} 
      POSTGRES_DB: ${DB_NAME} 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USERNAME -d $$DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_setup:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      args:
        SERVICE: dbsetup
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
    !!merge <<: *shared-env
        
networks:
  db:
    driver: bridge

volumes:
  db:
